version: "3.8"

services:
  api:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./
      dockerfile: cmd/api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
  webhook:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./
      dockerfile: cmd/webhook/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
  postgres:
    hostname: database
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/database/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_platform

volumes:
  pgdata: